import { chromium } from 'playwright';
const OUT = '/tmp/claude-0/-home-claude-pulz/bc7fd394-8c22-5c33-960d-95a1a7172d61/scratchpad/shots';
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
page.on('pageerror', (e) => errors.push(String(e)));
await page.goto('http://127.0.0.1:8123/index.html');
await page.waitForFunction(() => window.__app, null, { timeout: 30000 });
await page.waitForTimeout(3000);
await page.screenshot({ path: OUT + '/v2_menu.png' });
await page.evaluate(() => { const a = window.__app; a.press(a.panels.menu, 'settings'); a.press(a.panels.settings, 'sh:+'); a.game.logAttempt({ nm: 'Hook P', spd: 2.4, res: 'perfektní' }); a.game.logAttempt({ nm: 'Direkt L', spd: 0.6, res: 'slabý (min. 0.95)' }); a.game.logAttempt({ nm: 'Zvedák L', spd: 1.8, res: 'vedle o 4 cm' }); a.press(a.panels.settings, 'practice'); });
await page.waitForTimeout(2500);
await page.screenshot({ path: OUT + '/v2_settings.png' });
console.log(await page.evaluate(() => [window.__app.screen, window.__app.game.items.length, window.__app.game.practiceMode]), errors);
await browser.close();
